import '../models/subject_model.dart';

/// पढ़ो गुरु — Syllabus Data Service
/// Provides NCERT syllabus data for classes 6-12.
class SyllabusService {
  /// Get all subjects for a given class
  List<SubjectModel> getSubjects(String studentClass) {
    return _allSyllabus[studentClass] ?? _getDefaultSubjects();
  }

  /// Get all available classes
  List<String> get classes => _allSyllabus.keys.toList()..sort();

  /// Search chapters across all subjects
  List<ChapterModel> search(String query, String studentClass) {
    if (query.isEmpty) return [];
    final results = <ChapterModel>[];
    final subjects = getSubjects(studentClass);
    final lowerQuery = query.toLowerCase();

    for (final subject in subjects) {
      for (final chapter in subject.chapters) {
        if (chapter.title.toLowerCase().contains(lowerQuery) ||
            chapter.titleHindi.contains(query)) {
          results.add(chapter);
        }
      }
    }
    return results;
  }

  List<SubjectModel> _getDefaultSubjects() {
    return [
      SubjectModel(
        id: 'math',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        chapters: _mathChapters,
      ),
      SubjectModel(
        id: 'science',
        name: 'Science',
        nameHindi: 'विज्ञान',
        icon: '🔬',
        chapters: _scienceChapters,
      ),
    ];
  }

  // ─── Mock Syllabus Data ──────────────────────────────────

  final Map<String, List<SubjectModel>> _allSyllabus = {
    'Class 6': [
      SubjectModel(
        id: 'math_6',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        chapters: [
          ChapterModel(
            id: 'm6_1',
            title: 'Knowing Our Numbers',
            titleHindi: 'अपनी संख्याओं को जानना',
            chapterNumber: '1',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm6_2',
            title: 'Whole Numbers',
            titleHindi: 'पूर्ण संख्याएं',
            chapterNumber: '2',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm6_3',
            title: 'Playing with Numbers',
            titleHindi: 'संख्याओं के साथ खेलना',
            chapterNumber: '3',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'm6_4',
            title: 'Basic Geometrical Ideas',
            titleHindi: 'मूल ज्यामितीय अवधारणाएं',
            chapterNumber: '4',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm6_5',
            title: 'Understanding Elementary Shapes',
            titleHindi: 'प्रारंभिक आकारों को समझना',
            chapterNumber: '5',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm6_6',
            title: 'Integers',
            titleHindi: 'पूर्णांक',
            chapterNumber: '6',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm6_7',
            title: 'Fractions',
            titleHindi: 'भिन्न',
            chapterNumber: '7',
            questionCount: 30,
          ),
          ChapterModel(
            id: 'm6_8',
            title: 'Decimals',
            titleHindi: 'दशमलव',
            chapterNumber: '8',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'm6_9',
            title: 'Data Handling',
            titleHindi: 'आंकड़ों का प्रबंधन',
            chapterNumber: '9',
            questionCount: 14,
          ),
          ChapterModel(
            id: 'm6_10',
            title: 'Mensuration',
            titleHindi: 'क्षेत्रमिति',
            chapterNumber: '10',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm6_11',
            title: 'Algebra',
            titleHindi: 'बीजगणित',
            chapterNumber: '11',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm6_12',
            title: 'Ratio and Proportion',
            titleHindi: 'अनुपात और समानुपात',
            chapterNumber: '12',
            questionCount: 22,
          ),
        ],
      ),
      SubjectModel(
        id: 'sci_6',
        name: 'Science',
        nameHindi: 'विज्ञान',
        icon: '🔬',
        chapters: [
          ChapterModel(
            id: 's6_1',
            title: 'Food: Where Does It Come From?',
            titleHindi: 'भोजन: यह कहाँ से आता है?',
            chapterNumber: '1',
            questionCount: 12,
          ),
          ChapterModel(
            id: 's6_2',
            title: 'Components of Food',
            titleHindi: 'भोजन के घटक',
            chapterNumber: '2',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's6_3',
            title: 'Fibre to Fabric',
            titleHindi: 'रेशे से वस्त्र तक',
            chapterNumber: '3',
            questionCount: 14,
          ),
          ChapterModel(
            id: 's6_4',
            title: 'Sorting Materials into Groups',
            titleHindi: 'वस्तुओं का समूहीकरण',
            chapterNumber: '4',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's6_5',
            title: 'Separation of Substances',
            titleHindi: 'पदार्थों का पृथक्करण',
            chapterNumber: '5',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's6_6',
            title: 'Changes Around Us',
            titleHindi: 'हमारे चारों ओर के परिवर्तन',
            chapterNumber: '6',
            questionCount: 12,
          ),
          ChapterModel(
            id: 's6_7',
            title: 'Getting to Know Plants',
            titleHindi: 'पौधों को जानना',
            chapterNumber: '7',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's6_8',
            title: 'Body Movements',
            titleHindi: 'शरीर में गति',
            chapterNumber: '8',
            questionCount: 14,
          ),
          ChapterModel(
            id: 's6_9',
            title: 'The Living Organisms',
            titleHindi: 'सजीव एवं उनके लक्षण',
            chapterNumber: '9',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's6_10',
            title: 'Motion and Measurement',
            titleHindi: 'गति एवं दूरियों का मापन',
            chapterNumber: '10',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's6_11',
            title: 'Light, Shadows and Reflections',
            titleHindi: 'प्रकाश, छायाएं एवं परावर्तन',
            chapterNumber: '11',
            questionCount: 14,
          ),
          ChapterModel(
            id: 's6_12',
            title: 'Electricity and Circuits',
            titleHindi: 'विद्युत और परिपथ',
            chapterNumber: '12',
            questionCount: 16,
          ),
        ],
      ),
    ],
    'Class 7': [
      SubjectModel(
        id: 'math_7',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        chapters: [
          ChapterModel(
            id: 'm7_1',
            title: 'Integers',
            titleHindi: 'पूर्णांक',
            chapterNumber: '1',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm7_2',
            title: 'Fractions and Decimals',
            titleHindi: 'भिन्न और दशमलव',
            chapterNumber: '2',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'm7_3',
            title: 'Data Handling',
            titleHindi: 'आंकड़ों का प्रबंधन',
            chapterNumber: '3',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm7_4',
            title: 'Simple Equations',
            titleHindi: 'सरल समीकरण',
            chapterNumber: '4',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm7_5',
            title: 'Lines and Angles',
            titleHindi: 'रेखाएं और कोण',
            chapterNumber: '5',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm7_6',
            title: 'The Triangle and its Properties',
            titleHindi: 'त्रिभुज और उसके गुण',
            chapterNumber: '6',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'm7_7',
            title: 'Comparing Quantities',
            titleHindi: 'राशियों की तुलना',
            chapterNumber: '7',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm7_8',
            title: 'Rational Numbers',
            titleHindi: 'परिमेय संख्याएं',
            chapterNumber: '8',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm7_9',
            title: 'Perimeter and Area',
            titleHindi: 'परिमाप और क्षेत्रफल',
            chapterNumber: '9',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm7_10',
            title: 'Algebraic Expressions',
            titleHindi: 'बीजीय व्यंजक',
            chapterNumber: '10',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm7_11',
            title: 'Exponents and Powers',
            titleHindi: 'घातांक और घात',
            chapterNumber: '11',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm7_12',
            title: 'Symmetry',
            titleHindi: 'सममिति',
            chapterNumber: '12',
            questionCount: 14,
          ),
        ],
      ),
      SubjectModel(
        id: 'sci_7',
        name: 'Science',
        nameHindi: 'विज्ञान',
        icon: '🔬',
        chapters: [
          ChapterModel(
            id: 's7_1',
            title: 'Nutrition in Plants',
            titleHindi: 'पादपों में पोषण',
            chapterNumber: '1',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's7_2',
            title: 'Nutrition in Animals',
            titleHindi: 'जंतुओं में पोषण',
            chapterNumber: '2',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's7_3',
            title: 'Heat',
            titleHindi: 'ऊष्मा',
            chapterNumber: '3',
            questionCount: 14,
          ),
          ChapterModel(
            id: 's7_4',
            title: 'Acids, Bases and Salts',
            titleHindi: 'अम्ल, क्षारक और लवण',
            chapterNumber: '4',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's7_5',
            title: 'Physical and Chemical Changes',
            titleHindi: 'भौतिक एवं रासायनिक परिवर्तन',
            chapterNumber: '5',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's7_6',
            title: 'Respiration in Organisms',
            titleHindi: 'जीवों में श्वसन',
            chapterNumber: '6',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's7_7',
            title: 'Transportation in Animals',
            titleHindi: 'जंतुओं में परिवहन',
            chapterNumber: '7',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's7_8',
            title: 'Reproduction in Plants',
            titleHindi: 'पादपों में जनन',
            chapterNumber: '8',
            questionCount: 14,
          ),
          ChapterModel(
            id: 's7_9',
            title: 'Motion and Time',
            titleHindi: 'गति और समय',
            chapterNumber: '9',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's7_10',
            title: 'Electric Current',
            titleHindi: 'विद्युत धारा',
            chapterNumber: '10',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's7_11',
            title: 'Light',
            titleHindi: 'प्रकाश',
            chapterNumber: '11',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's7_12',
            title: 'Forests',
            titleHindi: 'वन',
            chapterNumber: '12',
            questionCount: 12,
          ),
        ],
      ),
    ],
    'Class 10': [
      SubjectModel(
        id: 'math_10',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        totalChapters: 14,
        chapters: [
          ChapterModel(
            id: 'm10_1',
            title: 'Real Numbers',
            titleHindi: 'वास्तविक संख्याएं',
            chapterNumber: '1',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm10_2',
            title: 'Polynomials',
            titleHindi: 'बहुपद',
            chapterNumber: '2',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm10_3',
            title: 'Pair of Linear Equations',
            titleHindi: 'दो चरों में रैखिक समीकरण',
            chapterNumber: '3',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm10_4',
            title: 'Quadratic Equations',
            titleHindi: 'द्विघात समीकरण',
            chapterNumber: '4',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm10_5',
            title: 'Arithmetic Progressions',
            titleHindi: 'समांतर श्रेणियां',
            chapterNumber: '5',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm10_6',
            title: 'Triangles',
            titleHindi: 'त्रिभुज',
            chapterNumber: '6',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'm10_7',
            title: 'Coordinate Geometry',
            titleHindi: 'निर्देशांक ज्यामिति',
            chapterNumber: '7',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm10_8',
            title: 'Introduction to Trigonometry',
            titleHindi: 'त्रिकोणमिति का परिचय',
            chapterNumber: '8',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm10_9',
            title: 'Some Applications of Trigonometry',
            titleHindi: 'त्रिकोणमिति के कुछ अनुप्रयोग',
            chapterNumber: '9',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm10_10',
            title: 'Circles',
            titleHindi: 'वृत्त',
            chapterNumber: '10',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm10_11',
            title: 'Areas Related to Circles',
            titleHindi: 'वृत्तों से संबंधित क्षेत्रफल',
            chapterNumber: '11',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm10_12',
            title: 'Surface Areas and Volumes',
            titleHindi: 'पृष्ठीय क्षेत्रफल और आयतन',
            chapterNumber: '12',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm10_13',
            title: 'Statistics',
            titleHindi: 'सांख्यिकी',
            chapterNumber: '13',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm10_14',
            title: 'Probability',
            titleHindi: 'प्रायिकता',
            chapterNumber: '14',
            questionCount: 14,
          ),
        ],
      ),
      SubjectModel(
        id: 'sci_10',
        name: 'Science',
        nameHindi: 'विज्ञान',
        icon: '🔬',
        chapters: [
          ChapterModel(
            id: 's10_1',
            title: 'Chemical Reactions and Equations',
            titleHindi: 'रासायनिक अभिक्रियाएं और समीकरण',
            chapterNumber: '1',
            questionCount: 24,
          ),
          ChapterModel(
            id: 's10_2',
            title: 'Acids, Bases and Salts',
            titleHindi: 'अम्ल, क्षारक और लवण',
            chapterNumber: '2',
            questionCount: 28,
          ),
          ChapterModel(
            id: 's10_3',
            title: 'Metals and Non-metals',
            titleHindi: 'धातु और अधातु',
            chapterNumber: '3',
            questionCount: 26,
          ),
          ChapterModel(
            id: 's10_4',
            title: 'Carbon and its Compounds',
            titleHindi: 'कार्बन और उसके यौगिक',
            chapterNumber: '4',
            questionCount: 30,
          ),
          ChapterModel(
            id: 's10_5',
            title: 'Life Processes',
            titleHindi: 'जीवन प्रक्रियाएं',
            chapterNumber: '5',
            questionCount: 32,
          ),
          ChapterModel(
            id: 's10_6',
            title: 'Control and Coordination',
            titleHindi: 'नियंत्रण एवं समन्वय',
            chapterNumber: '6',
            questionCount: 22,
          ),
          ChapterModel(
            id: 's10_7',
            title: 'Reproduction',
            titleHindi: 'जनन',
            chapterNumber: '7',
            questionCount: 26,
          ),
          ChapterModel(
            id: 's10_8',
            title: 'Heredity',
            titleHindi: 'आनुवंशिकता',
            chapterNumber: '8',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's10_9',
            title: 'Light - Reflection and Refraction',
            titleHindi: 'प्रकाश - परावर्तन और अपवर्तन',
            chapterNumber: '9',
            questionCount: 30,
          ),
          ChapterModel(
            id: 's10_10',
            title: 'The Human Eye',
            titleHindi: 'मानव नेत्र',
            chapterNumber: '10',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's10_11',
            title: 'Electricity',
            titleHindi: 'विद्युत',
            chapterNumber: '11',
            questionCount: 34,
          ),
          ChapterModel(
            id: 's10_12',
            title: 'Magnetic Effects of Current',
            titleHindi: 'विद्युत धारा के चुंबकीय प्रभाव',
            chapterNumber: '12',
            questionCount: 24,
          ),
          ChapterModel(
            id: 's10_13',
            title: 'Our Environment',
            titleHindi: 'हमारा पर्यावरण',
            chapterNumber: '13',
            questionCount: 16,
          ),
        ],
      ),
    ],

    // ─── Class 8 ────────────────────────────────────────
    'Class 8': [
      SubjectModel(
        id: 'math_8',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        chapters: [
          ChapterModel(
            id: 'm8_1',
            title: 'Rational Numbers',
            titleHindi: 'परिमेय संख्याएं',
            chapterNumber: '1',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm8_2',
            title: 'Linear Equations in One Variable',
            titleHindi: 'एक चर में रैखिक समीकरण',
            chapterNumber: '2',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm8_3',
            title: 'Understanding Quadrilaterals',
            titleHindi: 'चतुर्भुजों को समझना',
            chapterNumber: '3',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm8_4',
            title: 'Data Handling',
            titleHindi: 'आंकड़ों का प्रबंधन',
            chapterNumber: '4',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm8_5',
            title: 'Squares and Square Roots',
            titleHindi: 'वर्ग और वर्गमूल',
            chapterNumber: '5',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'm8_6',
            title: 'Cubes and Cube Roots',
            titleHindi: 'घन और घनमूल',
            chapterNumber: '6',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm8_7',
            title: 'Comparing Quantities',
            titleHindi: 'राशियों की तुलना',
            chapterNumber: '7',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm8_8',
            title: 'Algebraic Expressions',
            titleHindi: 'बीजीय व्यंजक',
            chapterNumber: '8',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm8_9',
            title: 'Mensuration',
            titleHindi: 'क्षेत्रमिति',
            chapterNumber: '9',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'm8_10',
            title: 'Exponents and Powers',
            titleHindi: 'घातांक और घात',
            chapterNumber: '10',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm8_11',
            title: 'Direct and Inverse Proportions',
            titleHindi: 'सीधा और प्रतिलोम समानुपात',
            chapterNumber: '11',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm8_12',
            title: 'Factorisation',
            titleHindi: 'गुणनखंडन',
            chapterNumber: '12',
            questionCount: 24,
          ),
        ],
      ),
      SubjectModel(
        id: 'sci_8',
        name: 'Science',
        nameHindi: 'विज्ञान',
        icon: '🔬',
        chapters: [
          ChapterModel(
            id: 's8_1',
            title: 'Crop Production and Management',
            titleHindi: 'फसल उत्पादन एवं प्रबंधन',
            chapterNumber: '1',
            questionCount: 22,
          ),
          ChapterModel(
            id: 's8_2',
            title: 'Microorganisms: Friend and Foe',
            titleHindi: 'सूक्ष्मजीव: मित्र एवं शत्रु',
            chapterNumber: '2',
            questionCount: 24,
          ),
          ChapterModel(
            id: 's8_3',
            title: 'Coal and Petroleum',
            titleHindi: 'कोयला और पेट्रोलियम',
            chapterNumber: '3',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's8_4',
            title: 'Combustion and Flame',
            titleHindi: 'दहन और ज्वाला',
            chapterNumber: '4',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's8_5',
            title: 'Conservation of Plants and Animals',
            titleHindi: 'पादप एवं जंतुओं का संरक्षण',
            chapterNumber: '5',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's8_6',
            title: 'Reproduction in Animals',
            titleHindi: 'जंतुओं में जनन',
            chapterNumber: '6',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's8_7',
            title: 'Reaching the Age of Adolescence',
            titleHindi: 'किशोरावस्था की ओर',
            chapterNumber: '7',
            questionCount: 22,
          ),
          ChapterModel(
            id: 's8_8',
            title: 'Force and Pressure',
            titleHindi: 'बल और दाब',
            chapterNumber: '8',
            questionCount: 24,
          ),
          ChapterModel(
            id: 's8_9',
            title: 'Friction',
            titleHindi: 'घर्षण',
            chapterNumber: '9',
            questionCount: 18,
          ),
          ChapterModel(
            id: 's8_10',
            title: 'Sound',
            titleHindi: 'ध्वनि',
            chapterNumber: '10',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's8_11',
            title: 'Chemical Effects of Current',
            titleHindi: 'विद्युत धारा के रासायनिक प्रभाव',
            chapterNumber: '11',
            questionCount: 16,
          ),
          ChapterModel(
            id: 's8_12',
            title: 'Some Natural Phenomena',
            titleHindi: 'कुछ प्राकृतिक घटनाएं',
            chapterNumber: '12',
            questionCount: 18,
          ),
        ],
      ),
    ],

    // ─── Class 9 ────────────────────────────────────────
    'Class 9': [
      SubjectModel(
        id: 'math_9',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        chapters: [
          ChapterModel(
            id: 'm9_1',
            title: 'Number Systems',
            titleHindi: 'संख्या पद्धति',
            chapterNumber: '1',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm9_2',
            title: 'Polynomials',
            titleHindi: 'बहुपद',
            chapterNumber: '2',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm9_3',
            title: 'Coordinate Geometry',
            titleHindi: 'निर्देशांक ज्यामिति',
            chapterNumber: '3',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm9_4',
            title: 'Linear Equations in Two Variables',
            titleHindi: 'दो चरों में रैखिक समीकरण',
            chapterNumber: '4',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm9_5',
            title: 'Introduction to Euclid Geometry',
            titleHindi: 'यूक्लिड की ज्यामिति का परिचय',
            chapterNumber: '5',
            questionCount: 14,
          ),
          ChapterModel(
            id: 'm9_6',
            title: 'Lines and Angles',
            titleHindi: 'रेखाएं और कोण',
            chapterNumber: '6',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm9_7',
            title: 'Triangles',
            titleHindi: 'त्रिभुज',
            chapterNumber: '7',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'm9_8',
            title: 'Quadrilaterals',
            titleHindi: 'चतुर्भुज',
            chapterNumber: '8',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm9_9',
            title: 'Circles',
            titleHindi: 'वृत्त',
            chapterNumber: '9',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm9_10',
            title: 'Heron Formula',
            titleHindi: 'हीरोन का सूत्र',
            chapterNumber: '10',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm9_11',
            title: 'Surface Areas and Volumes',
            titleHindi: 'पृष्ठीय क्षेत्रफल और आयतन',
            chapterNumber: '11',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm9_12',
            title: 'Statistics',
            titleHindi: 'सांख्यिकी',
            chapterNumber: '12',
            questionCount: 14,
          ),
        ],
      ),
      SubjectModel(
        id: 'sci_9',
        name: 'Science',
        nameHindi: 'विज्ञान',
        icon: '🔬',
        chapters: [
          ChapterModel(
            id: 's9_1',
            title: 'Matter in Our Surroundings',
            titleHindi: 'हमारे आस-पास के पदार्थ',
            chapterNumber: '1',
            questionCount: 24,
          ),
          ChapterModel(
            id: 's9_2',
            title: 'Is Matter Around Us Pure',
            titleHindi: 'क्या हमारे आस-पास के पदार्थ शुद्ध हैं',
            chapterNumber: '2',
            questionCount: 28,
          ),
          ChapterModel(
            id: 's9_3',
            title: 'Atoms and Molecules',
            titleHindi: 'परमाणु एवं अणु',
            chapterNumber: '3',
            questionCount: 30,
          ),
          ChapterModel(
            id: 's9_4',
            title: 'Structure of the Atom',
            titleHindi: 'परमाणु की संरचना',
            chapterNumber: '4',
            questionCount: 22,
          ),
          ChapterModel(
            id: 's9_5',
            title: 'The Fundamental Unit of Life',
            titleHindi: 'जीवन की मूलभूत इकाई',
            chapterNumber: '5',
            questionCount: 26,
          ),
          ChapterModel(
            id: 's9_6',
            title: 'Tissues',
            titleHindi: 'ऊतक',
            chapterNumber: '6',
            questionCount: 24,
          ),
          ChapterModel(
            id: 's9_7',
            title: 'Motion',
            titleHindi: 'गति',
            chapterNumber: '7',
            questionCount: 28,
          ),
          ChapterModel(
            id: 's9_8',
            title: 'Force and Laws of Motion',
            titleHindi: 'बल और गति के नियम',
            chapterNumber: '8',
            questionCount: 22,
          ),
          ChapterModel(
            id: 's9_9',
            title: 'Gravitation',
            titleHindi: 'गुरुत्वाकर्षण',
            chapterNumber: '9',
            questionCount: 24,
          ),
          ChapterModel(
            id: 's9_10',
            title: 'Work and Energy',
            titleHindi: 'कार्य और ऊर्जा',
            chapterNumber: '10',
            questionCount: 20,
          ),
          ChapterModel(
            id: 's9_11',
            title: 'Sound',
            titleHindi: 'ध्वनि',
            chapterNumber: '11',
            questionCount: 22,
          ),
          ChapterModel(
            id: 's9_12',
            title: 'Improvement in Food Resources',
            titleHindi: 'खाद्य संसाधनों में सुधार',
            chapterNumber: '12',
            questionCount: 18,
          ),
        ],
      ),
    ],

    // ─── Class 11 ───────────────────────────────────────
    'Class 11': [
      SubjectModel(
        id: 'math_11',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        chapters: [
          ChapterModel(
            id: 'm11_1',
            title: 'Sets',
            titleHindi: 'समुच्चय',
            chapterNumber: '1',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm11_2',
            title: 'Relations and Functions',
            titleHindi: 'संबंध और फलन',
            chapterNumber: '2',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm11_3',
            title: 'Trigonometric Functions',
            titleHindi: 'त्रिकोणमितीय फलन',
            chapterNumber: '3',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'm11_4',
            title: 'Complex Numbers',
            titleHindi: 'सम्मिश्र संख्याएं',
            chapterNumber: '4',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm11_5',
            title: 'Linear Inequalities',
            titleHindi: 'रैखिक असमिकाएं',
            chapterNumber: '5',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm11_6',
            title: 'Permutations and Combinations',
            titleHindi: 'क्रमचय और संचय',
            chapterNumber: '6',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'm11_7',
            title: 'Binomial Theorem',
            titleHindi: 'द्विपद प्रमेय',
            chapterNumber: '7',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm11_8',
            title: 'Sequences and Series',
            titleHindi: 'अनुक्रम और श्रेणी',
            chapterNumber: '8',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm11_9',
            title: 'Straight Lines',
            titleHindi: 'सरल रेखाएं',
            chapterNumber: '9',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm11_10',
            title: 'Conic Sections',
            titleHindi: 'शंकु परिच्छेद',
            chapterNumber: '10',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm11_11',
            title: 'Introduction to 3D Geometry',
            titleHindi: 'त्रिविमीय ज्यामिति का परिचय',
            chapterNumber: '11',
            questionCount: 14,
          ),
          ChapterModel(
            id: 'm11_12',
            title: 'Limits and Derivatives',
            titleHindi: 'सीमाएं और अवकलज',
            chapterNumber: '12',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'm11_13',
            title: 'Statistics',
            titleHindi: 'सांख्यिकी',
            chapterNumber: '13',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'm11_14',
            title: 'Probability',
            titleHindi: 'प्रायिकता',
            chapterNumber: '14',
            questionCount: 18,
          ),
        ],
      ),
      SubjectModel(
        id: 'sci_11',
        name: 'Physics',
        nameHindi: 'भौतिकी',
        icon: '⚡',
        chapters: [
          ChapterModel(
            id: 'p11_1',
            title: 'Physical World',
            titleHindi: 'भौतिक जगत',
            chapterNumber: '1',
            questionCount: 12,
          ),
          ChapterModel(
            id: 'p11_2',
            title: 'Units and Measurements',
            titleHindi: 'मात्रक और मापन',
            chapterNumber: '2',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'p11_3',
            title: 'Motion in a Straight Line',
            titleHindi: 'सरल रेखा में गति',
            chapterNumber: '3',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'p11_4',
            title: 'Motion in a Plane',
            titleHindi: 'समतल में गति',
            chapterNumber: '4',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'p11_5',
            title: 'Laws of Motion',
            titleHindi: 'गति के नियम',
            chapterNumber: '5',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'p11_6',
            title: 'Work, Energy and Power',
            titleHindi: 'कार्य, ऊर्जा और शक्ति',
            chapterNumber: '6',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'p11_7',
            title: 'System of Particles',
            titleHindi: 'कणों के निकाय',
            chapterNumber: '7',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'p11_8',
            title: 'Gravitation',
            titleHindi: 'गुरुत्वाकर्षण',
            chapterNumber: '8',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'p11_9',
            title: 'Mechanical Properties of Solids',
            titleHindi: 'ठोसों के यांत्रिक गुण',
            chapterNumber: '9',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'p11_10',
            title: 'Mechanical Properties of Fluids',
            titleHindi: 'तरलों के यांत्रिक गुण',
            chapterNumber: '10',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'p11_11',
            title: 'Thermal Properties of Matter',
            titleHindi: 'द्रव्य के तापीय गुण',
            chapterNumber: '11',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'p11_12',
            title: 'Thermodynamics',
            titleHindi: 'ऊष्मागतिकी',
            chapterNumber: '12',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'p11_13',
            title: 'Kinetic Theory',
            titleHindi: 'अणुगति सिद्धांत',
            chapterNumber: '13',
            questionCount: 14,
          ),
          ChapterModel(
            id: 'p11_14',
            title: 'Oscillations',
            titleHindi: 'दोलन',
            chapterNumber: '14',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'p11_15',
            title: 'Waves',
            titleHindi: 'तरंगें',
            chapterNumber: '15',
            questionCount: 16,
          ),
        ],
      ),
      SubjectModel(
        id: 'chem_11',
        name: 'Chemistry',
        nameHindi: 'रसायन विज्ञान',
        icon: '🧪',
        chapters: [
          ChapterModel(
            id: 'c11_1',
            title: 'Some Basic Concepts of Chemistry',
            titleHindi: 'रसायन विज्ञान की कुछ मूल अवधारणाएं',
            chapterNumber: '1',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'c11_2',
            title: 'Structure of Atom',
            titleHindi: 'परमाणु की संरचना',
            chapterNumber: '2',
            questionCount: 30,
          ),
          ChapterModel(
            id: 'c11_3',
            title: 'Classification of Elements',
            titleHindi: 'तत्वों का वर्गीकरण',
            chapterNumber: '3',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'c11_4',
            title: 'Chemical Bonding',
            titleHindi: 'रासायनिक बंधन',
            chapterNumber: '4',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'c11_5',
            title: 'States of Matter',
            titleHindi: 'द्रव्य की अवस्थाएं',
            chapterNumber: '5',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'c11_6',
            title: 'Thermodynamics',
            titleHindi: 'ऊष्मागतिकी',
            chapterNumber: '6',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'c11_7',
            title: 'Equilibrium',
            titleHindi: 'साम्यावस्था',
            chapterNumber: '7',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'c11_8',
            title: 'Redox Reactions',
            titleHindi: 'रेडॉक्स अभिक्रियाएं',
            chapterNumber: '8',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'c11_9',
            title: 'Hydrogen',
            titleHindi: 'हाइड्रोजन',
            chapterNumber: '9',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'c11_10',
            title: 's-Block Elements',
            titleHindi: 's-ब्लॉक तत्व',
            chapterNumber: '10',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'c11_11',
            title: 'p-Block Elements',
            titleHindi: 'p-ब्लॉक तत्व',
            chapterNumber: '11',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'c11_12',
            title: 'Organic Chemistry',
            titleHindi: 'कार्बनिक रसायन',
            chapterNumber: '12',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'c11_13',
            title: 'Hydrocarbons',
            titleHindi: 'हाइड्रोकार्बन',
            chapterNumber: '13',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'c11_14',
            title: 'Environmental Chemistry',
            titleHindi: 'पर्यावरणीय रसायन',
            chapterNumber: '14',
            questionCount: 16,
          ),
        ],
      ),
      SubjectModel(
        id: 'bio_11',
        name: 'Biology',
        nameHindi: 'जीव विज्ञान',
        icon: '🧬',
        chapters: [
          ChapterModel(
            id: 'b11_1',
            title: 'The Living World',
            titleHindi: 'जीव जगत',
            chapterNumber: '1',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'b11_2',
            title: 'Biological Classification',
            titleHindi: 'जैव वर्गीकरण',
            chapterNumber: '2',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'b11_3',
            title: 'Plant Kingdom',
            titleHindi: 'वनस्पति जगत',
            chapterNumber: '3',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'b11_4',
            title: 'Animal Kingdom',
            titleHindi: 'प्राणि जगत',
            chapterNumber: '4',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'b11_5',
            title: 'Morphology of Flowering Plants',
            titleHindi: 'पुष्पी पादपों की आकारिकी',
            chapterNumber: '5',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'b11_6',
            title: 'Anatomy of Flowering Plants',
            titleHindi: 'पुष्पी पादपों का शरीर',
            chapterNumber: '6',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'b11_7',
            title: 'Structural Organization in Animals',
            titleHindi: 'प्राणियों में संरचनात्मक संगठन',
            chapterNumber: '7',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'b11_8',
            title: 'Cell: The Unit of Life',
            titleHindi: 'कोशिका: जीवन की इकाई',
            chapterNumber: '8',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'b11_9',
            title: 'Biomolecules',
            titleHindi: 'जैव अणु',
            chapterNumber: '9',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'b11_10',
            title: 'Cell Cycle and Division',
            titleHindi: 'कोशिका चक्र और विभाजन',
            chapterNumber: '10',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'b11_11',
            title: 'Transport in Plants',
            titleHindi: 'पादपों में परिवहन',
            chapterNumber: '11',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'b11_12',
            title: 'Mineral Nutrition',
            titleHindi: 'खनिज पोषण',
            chapterNumber: '12',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'b11_13',
            title: 'Photosynthesis',
            titleHindi: 'प्रकाश-संश्लेषण',
            chapterNumber: '13',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'b11_14',
            title: 'Respiration in Plants',
            titleHindi: 'पादपों में श्वसन',
            chapterNumber: '14',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'b11_15',
            title: 'Plant Growth and Development',
            titleHindi: 'पादप वृद्धि और विकास',
            chapterNumber: '15',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'b11_16',
            title: 'Digestion and Absorption',
            titleHindi: 'पाचन और अवशोषण',
            chapterNumber: '16',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'b11_17',
            title: 'Breathing and Exchange of Gases',
            titleHindi: 'श्वसन और गैसों का विनिमय',
            chapterNumber: '17',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'b11_18',
            title: 'Body Fluids and Circulation',
            titleHindi: 'शरीर द्रव और परिसंचरण',
            chapterNumber: '18',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'b11_19',
            title: 'Excretory Products',
            titleHindi: 'उत्सर्जी उत्पाद',
            chapterNumber: '19',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'b11_20',
            title: 'Locomotion and Movement',
            titleHindi: 'गति और संचलन',
            chapterNumber: '20',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'b11_21',
            title: 'Neural Control and Coordination',
            titleHindi: 'तंत्रिकीय नियंत्रण और समन्वय',
            chapterNumber: '21',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'b11_22',
            title: 'Chemical Coordination',
            titleHindi: 'रासायनिक समन्वय',
            chapterNumber: '22',
            questionCount: 18,
          ),
        ],
      ),
    ],

    // ─── Class 12 ───────────────────────────────────────
    'Class 12': [
      SubjectModel(
        id: 'math_12',
        name: 'Mathematics',
        nameHindi: 'गणित',
        icon: '📐',
        chapters: [
          ChapterModel(
            id: 'm12_1',
            title: 'Relations and Functions',
            titleHindi: 'संबंध और फलन',
            chapterNumber: '1',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm12_2',
            title: 'Inverse Trigonometric Functions',
            titleHindi: 'प्रतिलोम त्रिकोणमितीय फलन',
            chapterNumber: '2',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm12_3',
            title: 'Matrices',
            titleHindi: 'आव्यूह',
            chapterNumber: '3',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'm12_4',
            title: 'Determinants',
            titleHindi: 'सारणिक',
            chapterNumber: '4',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'm12_5',
            title: 'Continuity and Differentiability',
            titleHindi: 'सांतत्य और अवकलनीयता',
            chapterNumber: '5',
            questionCount: 30,
          ),
          ChapterModel(
            id: 'm12_6',
            title: 'Applications of Derivatives',
            titleHindi: 'अवकलज के अनुप्रयोग',
            chapterNumber: '6',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'm12_7',
            title: 'Integrals',
            titleHindi: 'समाकलन',
            chapterNumber: '7',
            questionCount: 32,
          ),
          ChapterModel(
            id: 'm12_8',
            title: 'Applications of Integrals',
            titleHindi: 'समाकलन के अनुप्रयोग',
            chapterNumber: '8',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm12_9',
            title: 'Differential Equations',
            titleHindi: 'अवकल समीकरण',
            chapterNumber: '9',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'm12_10',
            title: 'Vector Algebra',
            titleHindi: 'सदिश बीजगणित',
            chapterNumber: '10',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'm12_11',
            title: 'Three Dimensional Geometry',
            titleHindi: 'त्रिविमीय ज्यामिति',
            chapterNumber: '11',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'm12_12',
            title: 'Linear Programming',
            titleHindi: 'रैखिक प्रोग्रामन',
            chapterNumber: '12',
            questionCount: 14,
          ),
          ChapterModel(
            id: 'm12_13',
            title: 'Probability',
            titleHindi: 'प्रायिकता',
            chapterNumber: '13',
            questionCount: 24,
          ),
        ],
      ),
      SubjectModel(
        id: 'phys_12',
        name: 'Physics',
        nameHindi: 'भौतिकी',
        icon: '⚡',
        chapters: [
          ChapterModel(
            id: 'p12_1',
            title: 'Electric Charges and Fields',
            titleHindi: 'विद्युत आवेश और क्षेत्र',
            chapterNumber: '1',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'p12_2',
            title: 'Electrostatic Potential',
            titleHindi: 'स्थिरवैद्युत विभव',
            chapterNumber: '2',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'p12_3',
            title: 'Current Electricity',
            titleHindi: 'विद्युत धारा',
            chapterNumber: '3',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'p12_4',
            title: 'Moving Charges and Magnetism',
            titleHindi: 'गतिमान आवेश और चुंबकत्व',
            chapterNumber: '4',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'p12_5',
            title: 'Magnetism and Matter',
            titleHindi: 'चुंबकत्व और द्रव्य',
            chapterNumber: '5',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'p12_6',
            title: 'Electromagnetic Induction',
            titleHindi: 'विद्युत चुंबकीय प्रेरण',
            chapterNumber: '6',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'p12_7',
            title: 'Alternating Current',
            titleHindi: 'प्रत्यावर्ती धारा',
            chapterNumber: '7',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'p12_8',
            title: 'Electromagnetic Waves',
            titleHindi: 'विद्युत चुंबकीय तरंगें',
            chapterNumber: '8',
            questionCount: 14,
          ),
          ChapterModel(
            id: 'p12_9',
            title: 'Ray Optics',
            titleHindi: 'किरण प्रकाशिकी',
            chapterNumber: '9',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'p12_10',
            title: 'Wave Optics',
            titleHindi: 'तरंग प्रकाशिकी',
            chapterNumber: '10',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'p12_11',
            title: 'Dual Nature of Radiation',
            titleHindi: 'विकिरण का द्वैत स्वभाव',
            chapterNumber: '11',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'p12_12',
            title: 'Atoms',
            titleHindi: 'परमाणु',
            chapterNumber: '12',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'p12_13',
            title: 'Nuclei',
            titleHindi: 'नाभिक',
            chapterNumber: '13',
            questionCount: 14,
          ),
          ChapterModel(
            id: 'p12_14',
            title: 'Semiconductor Electronics',
            titleHindi: 'अर्धचालक इलेक्ट्रॉनिकी',
            chapterNumber: '14',
            questionCount: 24,
          ),
        ],
      ),
      SubjectModel(
        id: 'chem_12',
        name: 'Chemistry',
        nameHindi: 'रसायन विज्ञान',
        icon: '🧪',
        chapters: [
          ChapterModel(
            id: 'c12_1',
            title: 'Solutions',
            titleHindi: 'विलयन',
            chapterNumber: '1',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'c12_2',
            title: 'Electrochemistry',
            titleHindi: 'वैद्युत रसायन',
            chapterNumber: '2',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'c12_3',
            title: 'Chemical Kinetics',
            titleHindi: 'रासायनिक गतिकी',
            chapterNumber: '3',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'c12_4',
            title: 'd and f Block Elements',
            titleHindi: 'd एवं f ब्लॉक के तत्व',
            chapterNumber: '4',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'c12_5',
            title: 'Coordination Compounds',
            titleHindi: 'उपसहसंयोजन यौगिक',
            chapterNumber: '5',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'c12_6',
            title: 'Haloalkanes and Haloarenes',
            titleHindi: 'हैलोऐल्केन और हैलोऐरीन',
            chapterNumber: '6',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'c12_7',
            title: 'Alcohols, Phenols and Ethers',
            titleHindi: 'ऐल्कोहॉल, फीनॉल और ईथर',
            chapterNumber: '7',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'c12_8',
            title: 'Aldehydes, Ketones',
            titleHindi: 'ऐल्डिहाइड, कीटोन',
            chapterNumber: '8',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'c12_9',
            title: 'Amines',
            titleHindi: 'एमीन',
            chapterNumber: '9',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'c12_10',
            title: 'Biomolecules',
            titleHindi: 'जैव अणु',
            chapterNumber: '10',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'c12_11',
            title: 'Polymers',
            titleHindi: 'बहुलक',
            chapterNumber: '11',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'c12_12',
            title: 'Chemistry in Everyday Life',
            titleHindi: 'दैनिक जीवन में रसायन',
            chapterNumber: '12',
            questionCount: 14,
          ),
        ],
      ),
      SubjectModel(
        id: 'bio_12',
        name: 'Biology',
        nameHindi: 'जीव विज्ञान',
        icon: '🧬',
        chapters: [
          ChapterModel(
            id: 'b12_1',
            title: 'Reproduction in Organisms',
            titleHindi: 'जीवों में जनन',
            chapterNumber: '1',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'b12_2',
            title: 'Sexual Reproduction in Plants',
            titleHindi: 'पुष्पी पादपों में लैंगिक जनन',
            chapterNumber: '2',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'b12_3',
            title: 'Human Reproduction',
            titleHindi: 'मानव जनन',
            chapterNumber: '3',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'b12_4',
            title: 'Reproductive Health',
            titleHindi: 'जनन स्वास्थ्य',
            chapterNumber: '4',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'b12_5',
            title: 'Principles of Inheritance',
            titleHindi: 'वंशागति के सिद्धांत',
            chapterNumber: '5',
            questionCount: 28,
          ),
          ChapterModel(
            id: 'b12_6',
            title: 'Molecular Basis of Inheritance',
            titleHindi: 'वंशागति का आणविक आधार',
            chapterNumber: '6',
            questionCount: 30,
          ),
          ChapterModel(
            id: 'b12_7',
            title: 'Evolution',
            titleHindi: 'विकास',
            chapterNumber: '7',
            questionCount: 24,
          ),
          ChapterModel(
            id: 'b12_8',
            title: 'Human Health and Disease',
            titleHindi: 'मानव स्वास्थ्य और रोग',
            chapterNumber: '8',
            questionCount: 26,
          ),
          ChapterModel(
            id: 'b12_9',
            title: 'Microbes in Human Welfare',
            titleHindi: 'मानव कल्याण में सूक्ष्मजीव',
            chapterNumber: '9',
            questionCount: 18,
          ),
          ChapterModel(
            id: 'b12_10',
            title: 'Biotechnology: Principles',
            titleHindi: 'जैव प्रौद्योगिकी: सिद्धांत',
            chapterNumber: '10',
            questionCount: 22,
          ),
          ChapterModel(
            id: 'b12_11',
            title: 'Biotechnology: Applications',
            titleHindi: 'जैव प्रौद्योगिकी: अनुप्रयोग',
            chapterNumber: '11',
            questionCount: 20,
          ),
          ChapterModel(
            id: 'b12_12',
            title: 'Organisms and Populations',
            titleHindi: 'जीव और समष्टियां',
            chapterNumber: '12',
            questionCount: 16,
          ),
          ChapterModel(
            id: 'b12_13',
            title: 'Ecosystem',
            titleHindi: 'पारितंत्र',
            chapterNumber: '13',
            questionCount: 18,
          ),
        ],
      ),
    ],
  };

  // Fallback chapters
  final _mathChapters = [
    ChapterModel(
      id: 'm1',
      title: 'Chapter 1',
      titleHindi: 'पाठ 1',
      chapterNumber: '1',
      questionCount: 20,
    ),
    ChapterModel(
      id: 'm2',
      title: 'Chapter 2',
      titleHindi: 'पाठ 2',
      chapterNumber: '2',
      questionCount: 18,
    ),
  ];

  final _scienceChapters = [
    ChapterModel(
      id: 's1',
      title: 'Chapter 1',
      titleHindi: 'पाठ 1',
      chapterNumber: '1',
      questionCount: 16,
    ),
    ChapterModel(
      id: 's2',
      title: 'Chapter 2',
      titleHindi: 'पाठ 2',
      chapterNumber: '2',
      questionCount: 20,
    ),
  ];
}
