name: padho_guru_server
description: पढ़ो Guru - Genkit AI Server for Cloud Run
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  genkit: ^0.14.1
  genkit_openai: ^0.3.4
  genkit_shelf: ^0.1.9
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
